using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    [SerializeField] AudioClip gunshot;
    [SerializeField] ParticleSystem gunFlash;
    public CharacterController controller;

    public float speed = 12f;
    public float gravity = -9.81f;
    float walkSpeed = 12f;
    public float jumpHeight = 3f;

    public Transform groundCheck;
    public float groundDistance = 0.4f;
    public LayerMask groundMask;

    
    AudioSource _gunAudio;
    

    Vector3 velocity;
    bool isGrounded;

    private void Awake()
    {
        _gunAudio = GetComponent<AudioSource>();
    }
    void Update()
    {

        isGrounded = Physics.CheckSphere(groundCheck.position, groundDistance, groundMask);

        if (isGrounded && velocity.y < 0)
        {
            velocity.y = -2f;
        }
        float x = Input.GetAxis("Horizontal");
        float z = Input.GetAxis("Vertical");

        Vector3 move = transform.right * x + transform.forward * z;

        controller.Move(move * speed * Time.deltaTime);

        if (Input.GetButtonDown("Jump") && isGrounded)
        {
            velocity.y = Mathf.Sqrt(jumpHeight * -2f * gravity);
        }

            velocity.y += gravity * Time.deltaTime;

        controller.Move(velocity * Time.deltaTime);

        if (Input.GetButtonDown("Fire1"))
        {
            playGunshot(gunshot);
            gunFlash.Play();
        }
        if(Input.GetKeyDown(KeyCode.LeftShift))
        {
            speed *= 1.75f;
        }
        if (Input.GetKeyUp(KeyCode.LeftShift))
        {
            speed = walkSpeed;
        }

       

    }

    public void playGunshot(AudioClip gunClip)
    {
        _gunAudio.clip = gunClip;
        _gunAudio.Play();
    }

    public void velReset()
    {
        velocity.y = 0;
    }
}
